spring.application.name=wow-afterlife-api

spring.datasource.url=jdbc:mysql://localhost:3306/acore_auth
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true